FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install -U pip
RUN pip install pipenv

COPY Pipfile .

#RUN pipenv lock

#RUN pipenv install --system --deploy
#RUN pipenv lock --clear
RUN pip install numpy==1.26.4 pandas scikit-learn fastparquet
COPY starter.py .
